## for batch of inputs

In [1]:
import numpy as np

In [2]:
inputs=np.array([[1,2,3],[4,5,6],[7,8,9]])
weights=np.random.random((4,3))
biases=np.random.randint(0,10,4)

output=np.dot(inputs,weights.T)+biases
print(output)

[[11.14336159  8.07806086 11.41829799  7.05007492]
 [18.01597411 11.48639922 15.65730942 12.43539102]
 [24.88858663 14.89473758 19.89632086 17.82070712]]
